### PR TITLE
Porting to SDL2

### PR DESCRIPTION
**Pull request by ntfshard**
Hello

I made several changes for porting to SDL2.
I took Cmake/Modules from another your repo

assert removed cause new doesn't return NULL by default (you should pass std::nothrow for it)

I leave some hardcoded pathes in Cmake for Linux (I had no idea about it)

Tested: linux opensuse x64, libSDL 2.0.3-7.2

PS I didn't install your libraries - just sourced some environment (and small hack in Cmake and renaming files[it's really odd name for so starts with underscore _fife.so ])
  export LIBRARY_PATH=/home/$u/src/fifechan:/home/$u/src/fifengine/build/engine/release
  export CPATH=/home/$u/src/fifengine/engine/core/:/home/$u/src/fifechan/include
  export LD_LIBRARY_PATH=/home/$u/src/fifechan:/home/$u/src/fifengine/build/engine/release

It could be great if you can create some metarepository with all subrepo and common building target ;)

--M

### CODE REVIEW

**Comment by prock-fife** [comment]
Excellent!  Thanks for the contribution.  We should set travis up to actually build this.  I'm assuming this works with FIFE master?

**Comment by ntfshard** [comment]
I checked it with libraries from master.

**Comment by prock-fife** [comment]
Does the tutorial run fine?  If so it's safe to merge this.

**Comment by ntfshard** [comment]
Now it works fine; I should check it twice; Shame on me =)

**Pull request merged**
